name: 'Setup Maven Settings'
description: 'Configure a settings.xml file with access to Bonitasoft Artifactory'
inputs:
  KSM_CONFIG:
    description: 'The Keeper Secret Manager configuration'
    required: true

runs:
  using: "composite"
  steps:
    - name: Retrieve Artifactory secrets from Keeper
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_JFROG_RECORD_ID }}/field/login > env:JFROG_USER
            ${{ vars.KEEPER_JFROG_RECORD_ID }}/field/password > env:JFROG_TOKEN
    - name: Setup Maven configuration
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://bonitasoft.jfrog.io/artifactory/releases",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://bonitasoft.jfrog.io/artifactory/snapshots",
              "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
                "id": "ossrh-snapshots",
                "name": "ossrh-snapshots",
                "url" : "https://oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://bonitasoft.jfrog.io/artifactory/releases",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://bonitasoft.jfrog.io/artifactory/snapshots",
              "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
                "id": "ossrh-snapshots",
                "name": "ossrh-snapshots",
                "url" : "https://oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                "enabled": "false"
                },
                "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "releases",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            },
            {
              "id": "snapshots",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            }
          ]
          