name: Setup Maven Settings
description: Configure a settings.xml file with access to Bonitasoft Artifactory
author: Bonitasoft

inputs:
  keeper-secret-config:
    description: The Keeper Secret Manager configuration
    required: true

runs:
  using: composite
  steps:
    - name: Retrieve Artifactory secrets from Keeper
      uses: Keeper-Security/ksm-action@v1
      with:
        keeper-secret-config: ${{ inputs.keeper-secret-config }}
        secrets: |
          YPOU0laqe0V0mq_qwQ_3wg/field/login > env:JFROG_USER
          YPOU0laqe0V0mq_qwQ_3wg/field/password > env:JFROG_TOKEN
          9aU6tget4-Q-1alHvAIp5g/field/login > env:OSSRH_USERNAME
          9aU6tget4-Q-1alHvAIp5g/field/password > env:OSSRH_PSW
          1W-qBXHmaENw-ZmeMzDS4A/field/login > env:GPG_KEYNAME
          1W-qBXHmaENw-ZmeMzDS4A/custom_field/gpg-private-key > env:GPG_PRIVATE_KEY
          1W-qBXHmaENw-ZmeMzDS4A/field/password > env:MAVEN_GPG_PASSPHRASE

    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
        passphrase: ${{ env.MAVEN_GPG_PASSPHRASE }}
        fingerprint: ${{ env.GPG_KEYNAME }}
 
    - name: Setup Maven configuration
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        profiles: >
          [ 
            {
              "id" : "gpg",
              "properties": {
                "gpg.keyname": "${{ env.GPG_KEYNAME }}"
              }
            }
          ]
        active_profiles: >
         [
           "gpg",
           "github"
         ]
        repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://bonitasoft.jfrog.io/artifactory/releases",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://bonitasoft.jfrog.io/artifactory/snapshots",
              "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
                "id": "ossrh-snapshots",
                "name": "ossrh-snapshots",
                "url" : "https://oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
              "id": "ext-release-local",
              "name": "ext-release-local",
              "url": "https://bonitasoft.jfrog.io/artifactory/ext-release-local",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://bonitasoft.jfrog.io/artifactory/releases",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://bonitasoft.jfrog.io/artifactory/snapshots",
              "releases": {
                "enabled": "false"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
                "id": "ossrh-snapshots",
                "name": "ossrh-snapshots",
                "url" : "https://oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                "enabled": "false"
                },
                "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "releases",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            },
            {
              "id": "snapshots",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            },
            {
              "id": "staging",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            },
            {
              "id": "ossrh",
              "username": "${{ env.OSSRH_USERNAME }}",
              "password": "${{ env.OSSRH_PSW }}"
            },
            {
              "id": "ext-release-local",
              "username": "${{ env.JFROG_USER }}",
              "password": "${{ env.JFROG_TOKEN }}"
            }
          ]
